### ISSUE TITLE
Engine (Curve25519) Integration in a Litex SoC

### ISSUE THREAD

**Issue by rdolbeau** [betrusted-io/gateware#5]
Hello,

I'm trying to integrate the Curve25519 Engine in my own Litex SoC. Beware that I'm a hardware newbie and could have overlooked/ignored/missed something obvious...

My SoC does not have an embedded CPU, as it is used as extra peripherals for an existing host [1].

Simply adding the device to the primary SoC caused some timing issues even at low frequencies (which might have been a symptom that I shouldn't have worked around...).

As a workaround, I integrated it in its own set of clock domains, with a Wishbone CDC between the main Wishbone and the Engine. I then [rename every ClockDomain](https://github.com/rdolbeau/SBusFPGA/blob/42c508688547073bd6245da5e6bb11fcaec165f3/sbus-to-ztex-gateware-migen/sbus_to_fpga_soc.py#L280-L282), and I've updated the Engine constraint to use `clk50`/`clk100`/`clk200` (which only needed renaming `sysclk` to `clk100`). I generate the clocks from a single S7MMCM and made sure I defined the [system clock constraint by hand](https://github.com/rdolbeau/SBusFPGA/blob/42c508688547073bd6245da5e6bb11fcaec165f3/sbus-to-ztex-gateware-migen/sbus_to_fpga_soc.py#L49-L58) rather than with the Litex command so that the Engine-specific constraints are properly parsed. As nothing from the Engine run in `sys` I have false path constraints between `sys` and `clk50`/`clk100`/`clk200`, both ways, thus avoiding any timing issues there (again, perhaps wrongly...).

BTW, the clock names are a lie; the actual clocks are generated at 40/80/160 MHz to make sure I have a bit of margin (and with this mechanism, Vivado is happy with the timings even at 55/110/220 Mhz for my Artix-7).

I've also added a small NetBSD driver to the host. It can read/write the CSRs and the two Wishbone-mapped area (microcode, registers), using the same hardware mechanisms as the other devices on the Wishbone.

At boot-time the driver turns on the power bits (although I do not gate the clocks in any way, they are all always active, but I understand some internals of the Engine are enabled/disabled by that bit) and [initializes the microcode](https://github.com/rdolbeau/SBusFPGA/blob/42c508688547073bd6245da5e6bb11fcaec165f3/NetBSD/9.0/usr/src/sys/dev/sbus/sbusfpga_curve25519engine.c#L448) with a [trivial program](https://github.com/rdolbeau/SBusFPGA/blob/42c508688547073bd6245da5e6bb11fcaec165f3/NetBSD/9.0/usr/src/sys/dev/sbus/sbusfpga_curve25519engine.c#L312-L318) (it just sets two registers to some of the constants), along with the window/mpstart/mplen registers. Then I have an IOCTL that copies userland data to the registers, starts the engine, wait for it to stop running, and copy back the results to the userland data.

Up to this point, everything seems to work as expected, and my userland code sees the constants in the appropriate fields of the IOCTL data :-)

However - if I repeat the procedure multiple times (re-starting the userland process by hand, so with a comparatively slow turnaround), then eventually it fails: I get the wrong results, and if I keep repeating it converges quickly to having all-1 registers. As that stage, write-after-read on the registers fails in the driver before even trying to run the program. No idea if it's the write or the subsequent read that fails. As far as I can tell, the Wishbone bus and my bridge are still alive at that stage (I have a USB host controller on the Wishbone doing a lot of DMAs in the background and that still seem to be working).

Any insights/suggestions/advice on why the Engine is failing in that weird way would be welcome!

[1] Specifically a 1994 SPARCstation 20, project is [SBusFPGA](https://github.com/rdolbeau/SBusFPGA)

**Comment by bunnie** [comment]
interesting application for the engine. What FPGA are you using, and which speed grade?

Definitely, the timing is tricky. I see you mention the `clk50`/`clk100`/`clk200` -- `mul_clk` is aliased to `clk100`, did you catch that in your renaming?

In terms of the clock gating, should be fine not to gate them, however, you should still use the `power` `on` field (that is, switch it from the off->on state even if it seems to do nothing), because it also ensures that the `clk50` domain is phase-synchronized to the `clk100` domain at the off->on transition. The condition you describe sounds a little bit like maybe those are de-synched.

There's two possible phase relationships for clk50 vs clk100:

```
clk50  0011
clk100 0101
```
and 
```
clk50  0011
clk100 1010
```
It's very important that they have the correct phase relationship, otherwise reads and writes to the register files don't work. Basically, a lot of the timing constraints that relax the timing tell the timing engine "I promise I won't change the data on you for two clock cycles", and if you get the phase relationship wrong you end up breaking that promise.

That's the first thought that came to mind. 

I would imagine that in general most FPGA dev boards you get will be faster than the Spartan-7 part we're using on Precursor -- we're using the `-1L` speed grade, which is the slowest part of them all, so I imagine at the end of the day you should have an easier time of meeting timing within the engine, as long as you haven't packed the device more than ~60-70% full.

**Comment by rdolbeau** [comment]
Thanks for your answer.

The board is using an Artix-7, speed grade 1. I think it should be at least comparable to a Spartan 7, and I'm lowering the clocks a bit anyway to be on the safe side during development. The host's 60 MHz SuperSPARC shouldn't be difficult to outrun :-)

Yes, mul_clk is renamed to clk100, same as sys_clk. At first I forgot to rename sys_clk, and that _really_ didn't work; when I did it, things started looking better.

I do use the 'power on' field. At first I was enabling it once and for all at boot time; I now switch it on before use, then off afterwards (after I noticed it was doing something inside the engine, not just in clock handling), but it doesn't seem to help.

Which of the two phase relationships is the correct one (guessing first?), and how would I verify / ensure it ? From your answer it seems that is should be done automatically when turning the power flags on, so turning it on/off for every use should be better, but I don't think I saw much of an improvement, if any. Is the synchronization done purely inside the Engine, or does it rely on the clocks being actually reset on/off from the outside ? (I ask because I see a `ResetSignal("eng_clk")` in that area of the code).

Could the clocks (or their phases) be drifting over time between the different clocks, even though they come from the same S7MMCM ?

**Comment by bunnie** [comment]
![image](https://user-images.githubusercontent.com/1168375/126905961-a2e5c874-d7ed-4f55-b6f3-ca574b36495c.png)
The image above captures the expected phase arrangement for the clocks.

![image](https://user-images.githubusercontent.com/1168375/126905998-f92523b1-c70a-457e-adfe-5a948d84208b.png)
And this image shows the salient bits of the `on` reset synchronization happening.

It's assumed that the `clk50`, `clk100`, and `clk200` are all generated from the same `MCME` primitive. If that is the case, they will be guaranteed to be phase-locked, with no phase drift between them since they are all divided from the same VCO.

I do expect that you're using the Litex standard reset injection on the clocks; if you're suppressing reset signals and not using the `locked` output of the PLL to train the reset then you could end up with issues (this is basically the default if you're using the latest Litex PLL primitives, so if you don't know what I'm talking about, you're probably doing it right). 

Hm actually, now that I'm reading your OP -- you're saying that actually the first time you run your code, it works as expected. The issue is repeated runs seem to be failing?

**Comment by rdolbeau** [comment]
Yes, at first it seems to work then eventually fails. Although I've had system boots when even the first attempt would fail.

But I might not do the reset of the clocks right: they are all reset when the host bus (the SBus) sends a reset (i.e. when the host itself reset, cold or warm). This bus part lives in its own clock domain, also supplied by the host bus (and it's not fixed-frequency, my default host is the maximum of 25 MHz but it could be anywhere from 16.66 to 25 MHz), so the reset starts/stops in a completely asynchronous way to everything else in the system...

I will have to investigate and understand the reset scheme for Litex, the clocks and the Engine.

Thanks for the advice & and the waves, that should help me understand what's going on!

**Comment by bunnie** [comment]
Ah yes. It does smell a bit like a clock-sync issue. The four-phase register file scheme is definitely a timing hairball, there's more than once I've shot myself in the foot while tweaking something else in the system and breaking the reset-sync, so I could see a corner case gone missing in that scheme versus your use case.

The fact that it works even once points more toward clock-sync issue than static timing issue. The static timing issues will be data-dependent, but generally fairly repeatable.

**Comment by rdolbeau** [comment]
Finally found the (an?) issue; a different device in the design seemed to be wrecking havoc with the Engine (!). If I don't enable its driver, the Engine becomes deterministic (though every once in a while it won't start when I write 1 to 'on', still on it). And that's despite the fact that device works fine apparently (it's a USB controller and I can use a USB mouse on it with no apparent issue - other than causing almost every other device on the design to misbehave, that is).

Anyway I'm trying the Engine without the USB for now, thanks for the help.

~~Now I need to figure out what the program from montgomery.rs is really doing, as I can't match results with the implementations in C I found in OpenSSL and HACL* ... (I think I have the endianess OK as if I do a trivial program that writes constants in the registers and multiply them, I get back the result I expect). Is there some 'sample' values somewhere I could try as reference?~~ Now I have it; I had understood the parameters backward... Now onto performance :-)

**Comment by rdolbeau** [comment]
@bunnie FYI, I slightly updated the 'microcode' (https://github.com/rdolbeau/SBusFPGA/blob/6d142636c2553d2d20a21cac1963caca10aa6b90/sbus-to-ztex-gateware-migen/engine_code/engine_code.rs#L270) to initialize the constant part of the inputs before the loop (fewer transfers of data, also added 254 as constant #10 in the Engine for the loop count) and removed some of the PSAs (which were already flagged as somewhat redundant). Didn't measure performance, but I assume fewer instructions in the inner loop == faster on such a 1-instruction-per-cycle design :-)
